<?php

/*Do not edit this file manually. This copy of global file is overwritten by extensions editor.*/

$installed_extensions = array (
  1 => 
  array (
    'name' => 'Theme Anterp',
    'package' => 'anterp',
    'version' => '0.1-1',
    'type' => 'theme',
    'active' => false,
    'path' => 'themes/anterp',
  ),
  2 => 
  array (
    'name' => 'Theme Bluecollar',
    'package' => 'bluecollar',
    'version' => '0.1-1',
    'type' => 'theme',
    'active' => false,
    'path' => 'themes/bluecollar',
  ),
);
